name: Test and coverage

on: 
   pull_request:
        branches:
            - 'master/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install Ruby dependencies
        run: bundle update --bundler && bundle install
      - name: Run script
        run: bashcov script.sh
      - name: Upload reports to Codecov
        run: bash <(curl -s https://codecov.io/bash) -Z
      - name: Create code coverage status for the current commit
        run: |
          curl "https://{GIT_USER}:${GIT_TOKEN}@api.github.com/repos/${ORG_NAME}/${PROJECT_NAME}/statuses/${COMMIT_SHA}" -d "{\"state\": \"pending\",\"target_url\": \"https://github.com/${ORG_NAME}/${PROJECT_NAME}/pull/${PULL_NUMBER}/checks?check_run_id=${RUN_ID}\",\"description\": \"in progress — This check has started... \",\"context\": \"code cov\"}"
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USER: ${{ secrets.GIT_USER }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          RUN_ID: ${{ github.run_id }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}
          
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Running Tests
        run: echo 'Running test'
  report:
    needs: test 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
          fetch-depth: 2
     - uses: actions/upload-artifact@v2
       with:
        name: my-artifact
        path: test.txt
  
    
