# This is a basic workflow to help you get started with Actions

on:
  release:
    types: [published]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sh testrelease.sh
  QATest:
     needs : build
     runs-on: ubuntu-latest
     steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
           workflow_file_name: depentent.yml
           github_token: ${{ secrets.GIT_TOKEN }}
           owner: sameelpoc
           repo: Test1
           ref: main
           wait_interval: 10
           inputs: '{"commit_message": ${{github.event.head_commit.message}},"commit_id": ${{github.sha}}}'
           propagate_failure: true
           trigger_workflow: true
           wait_workflow: true    
